category_list = {
    0: "None_of_the_above",
    1: "Fruit",
    2: "Vegetables",
    3: "Dairy & Eggs",
    4: "Meat",
    5: "Fish",
    6: "Beverages",
    7: "Canned Goods",
    8: "Sauces, Oil & Vinegar",
    9: "Dry Goods",
    10: "Chips & Candy",
    11: "Breakfast Cereals",
    12: "Bakery",
    13: "Health & Beauty",
    14: "Home Goods & Food Storage",
    15: "Alcoholic Beverages",
    16: "Laundry and Cleaning Products",
    17: "Pets",
    18: "Frozen Food",
    19: "Baby",
    20: "International",
}